modLoader="javafml"
loaderVersion="[45,)"
license="BWL"
[[mods]]
modId="beautifulworld"
version="${file.jarVersion}"
displayName="Beautiful world"
logoFile=""
credits="Thanks for this example mod goes to Java"
authors="SkylightModding X GES"
description='''
desc
'''

[[dependencies.beautifulworld]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.beautifulworld]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
